name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configuração do JDK e build do projeto
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Build with Maven
      run: mvn clean package

    # Teste da aplicação
    - name: Run Tests
      run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Checkout do código do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build e push da imagem Docker
    - name: Build and Push Docker Image
      run: |
        docker build -t <docker-username>/projetoredes:latest .
        docker push <docker-username>/projetoredes:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    # Configuração para Deploy na EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /path/to/your/private/key.pem ubuntu@<EC2_PUBLIC_IP> << 'EOF'
        docker pull <docker-username>/projetoredes:latest
        docker stop projetoredes || true
        docker rm projetoredes || true
        docker run -d --name projetoredes -p 80:8080 <docker-username>/projetoredes:latest
        EOF
